<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>${title}</title>
<!--#include virtual="/keyword.shtml"--><!--#include virtual="/css_js.shtml"-->
<link rel="stylesheet" type="text/css" href="/style/info.css"/>
<script src="/js/jquery.qrcode.min.js" type="text/javascript" charset="utf-8"></script>
<script>
function showpic(index,url){
    if($(eval("pic"+index)).css('display')=='block'){
		$(eval("wx"+index)).html('');
		$(eval("pic"+index)).css('display','none');
		}else{
		$(eval("wx"+index)).qrcode({width:88,height:88,correctLevel:0,text:url});
		$(eval("pic"+index)).css('display','block');
    }}
</script>
</head>
<body oncontextmenu="return false" ondragstart="return false" onselectstart="return false" onselect="document.selection.empty()" oncopy="document.selection.empty()" onbeforecopy="return false">
    <div class="navbar navbar-fixed-top" style="_position: relative;_z-index: 10000;">
		<div class="navbar-inner">
			<div class="container">
				<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</a>
				<div class="nav-collapse">
					<!--#include virtual="/nav.shtml" -->
				</div>
				<ul class="nav pull-right login-none nav-tips">
		<li class="ie6png divider-vertical" style="_width: 30px;_height: 40px;_background: url(images/icons.png) no-repeat 10px -106px;"><a class="dropdown-toggle clearfix" href="/login.html?url=aHR0cDovL3d3dy5iaW9kaXNjb3Zlci5jb20vbmV3cy5odG1sP3BhZ2U9Mg%3D%3D" style="padding: 7px 5px;"></a></li>
	</ul>
<div class="popup-div tips-div" style="position: absolute;z-index: 10000001;display: none;"></div>
<ul class="nav pull-right pl-20 myul">
	<!--
    <li class=""><a href="register.html">注册</a></li>
    <li class="l10"><a href="login.html">登录</a></li>
	-->
</ul>
			</div>
		</div>
	</div>
    
    <div class="top-div">
		<!--#include virtual="/i_s/adtop.shtml" -->
	</div>
	</div>
</div>
<!--头部代码结束-->
 	<div class="hr tp-div-nexthr" style="margin-top: 0;margin-bottom: 0;padding: 0;"></div>
	<div class="container pb-15">
	<!-- Example row of columns -->
	<div class="row">
		<div class="span12">
 <!--内容页面-->     
                        
  <div class="label-div b-30 border-all pt-5 t-20" style="position: relative; padding-left: 0;">
   <div style="margin-top: 14px;" class="clearfix pb-12 pl-25 pr-25">
						<h1 class="pull-left r-10">青豆泥</h1>
						<div class="pull-left pt-5 none-768" style="_margin-top:-33px; _margin-left:-10px;"> 
                        <span class="like-plug-gz clearfix pull-left r-15">
                        <span class="count pull-left t-5 d-none"></span>
                        </span>
                        </div>
	</div>
   
 
   
  <div style="margin-top: 4px;" class="clearfix pl-25 pr-25">
						<div class="pull-left">
				 
				<span class="r-15 pull-left"></span>
		</div> 
 </div> 
  
 <div class="view-main t-20 pl-25 pr-25">
 
  <table style="width: 100%;" class="fc333 border-all">
		<tbody><tr>
			<td style="padding: 5px 12px;width: 25px;font-size: 22px;text-align: center;background: #E8E8E8; line-height: 30px;color: #999">导读</td>
			<td style="padding: 10px 10px 12px;line-height: 24px;">青豆中富含人体所需的各种营养物质，尤其是含有优质蛋白质，可以提高人体的抗病能力和康复能力。（适合7个月以上宝宝）</td>
			</tr>
	</tbody></table>
    
    <div class="view-content" style="margin-top: 18px;">
				<P>青豆中富含人体所需的各种营养物质，尤其是含有优质蛋白质，可以提高人体的抗病能力和康复能力。另外，青豆中富含粗纤维，能促进大肠蠕动，保持大便能畅，起到清洁大肠的作用。</P>
				<P>主料：青豆</P>
				<P>调料：母乳或配方奶</P>
				<P align=center><IMG title=鲫鱼汤 alt=鲫鱼汤 src="0101.jpg" border=0></P>
				<P><b>做法</b></P>
				<P>1、准备食材：青豆（煮）1碗、配方奶或母乳适量</P>
				<P>2、青豆加水煮开转小火，煮15分钟左右，煮至青豆软烂，煮好的青豆放凉，用手反复抓洗青豆，使豆壳和豆泥分离。</P>
  			<P>3、淘米的篮子放在一个干净的盆上，把抓洗好的青豆连水一起倒进去，把豆壳过滤出来。</P>
  			<P>4、把过滤豆壳的青豆放进搅拌机中搅拌均匀。</P>
  			<P>5、倒出搅拌好的豆泥。</P>
  			<P>6、豆泥水倒入布袋里挤干水份即可，倒入适量母乳或配方奶即可。</P>
  </div>
  </div> 
   
  <!--警告：切勿删除-->
  <!--[if IE 6]> <a class="follow-btn ie6png mmmzw"></a><![endif]--> 
</div>


<!---代码分享-->
<div class="t-10 label-div border-all pr-5   pb-10 pl-20 clearfix">
		<div class="share share-plug">
		<span style="height: 28px;line-height: 28px;color: #000;" class="pull-left r-10">分享到：</span>
			<div style="margin-top: 7px;" class="pull-left clearfix">
		    <a href="http://v.t.sina.com.cn/share/share.php?url=http://www.51per.com/jk/2014/01/01/c01.html&title=青豆泥中富含人体所需的各种营养物质，尤其是含有优质蛋白质，可以提高人体的抗病能力和康复能力。" target="_blank" class="bio_button_sina pull-left ie6png r-10 ">新浪微博</a>
    		<a href="http://v.t.qq.com/share/share.php?url=http://www.51per.com/jk/2014/01/01/c01.html&title=青豆泥中富含人体所需的各种营养物质，尤其是含有优质蛋白质，可以提高人体的抗病能力和康复能力。" target="_blank" class="bio_button_sina pull-left ie6png r-10 ">腾讯微博</a> 
			<a href="http://tieba.baidu.com/f/commit/share/openShareApi?url=http://www.51per.com/jk/2014/01/01/c01.html&title=hello&desc=&pic=" target="_blank" class="bio_button_sina pull-left ie6png r-10 ">百度贴吧</a>
			<a href="http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url=http://www.51per.com/jk/2014/01/01/c01.html" target="_blank" class="bio_button_sina pull-left ie6png r-10 ">QQ空间</a>
			<a class="bio_button_sina pull-left ie6png r-10" href="javascript:void(0)" onmouseover="showpic(0,'http://www.51per.com/jk/2014/01/01/c01.html');">
			微信扫一扫<div id="pic0" class="qr on" style="display:none"><br>
				<div id="wx0" /></div>
			</div></a> 
    	</div>
    	<div style="margin-top: 3px; margin-left: 20px;" class="pull-right">
    		<iframe width="136" scrolling="no" height="24" frameborder="0" src="http://widget.weibo.com/relationship/followbutton.php?language=zh_cn&amp;width=116&amp;height=24&amp;uid=2117966477&amp;style=2&amp;btn=red&amp;dpc=0" border="0" marginheight="0" marginwidth="0" allowtransparency="true"></iframe>
    	</div>					
    </div>
</div>
<!---代码分享-->

</div>
      <!--右侧代码-->  
       <div class="span4">
             <div class="t-20 mygz">
                 <dl>
				 <!--
                  <dd><p class="t">关注</p><p>1</p></dd>
                  <dd class="border"><p class="t">分享</p><p>0</p></dd>
                  <dd><p class="t">讨论</p><p>2</p></dd>
				  -->
                 <div class="mmclear"></div>                
                 </dl>
			</div>
        
       <!--#include virtual="/jk/info_r1.shtml" -->
			 <!--#include virtual="/jk/info_ad_r1.shtml" -->
			 <!--#include virtual="/jk/info_r2.shtml" -->
			 <!--#include virtual="/jk/info_ad_r2.shtml" -->
		</div>
	</div>
</div>

<!--#include virtual="/ad_footer.shtml" -->
</div>
<!--#include virtual="/i_s/footer.shtml" -->
</body>
</html>